#BIG NOTE, RULE ALL HAS TO UPDATED WITH THE MOST RECENT OUTPUT TO WORK
#This pipeline only works for single end reads right now?
import yaml
import subprocess
subprocess.run(["python", "sim_real_reads.py"], check = True)


configfile: "config_reads.yaml"

REAL_SAMPLES = config["real_reads"]
SIM_SAMPLES = config["sim_reads"]

print("Real Samples:", REAL_SAMPLES[:10])
print("Simulated samples:", SIM_SAMPLES)



#rule all defines the ultimate output of the 
rule all:
    input:
        "../chip_output/mac2_output/ann_peaks.txt"



def get_cut_input(wildcards):
        if wildcards.sample in SIM_SAMPLES:
        
            return f"../chip_output/chip_reads/{wildcards.sample}.fastq"
        else:
            return f"../chip_output/chip_cutadapt/cut_{wildcards.sample}.fastq"


rule cutadapt:
    input:
        "../data/{sample}.fastq"
    output:
        "../chip_output/chip_cutadapt/cut_{sample}.fastq"
    shell:
        """
        mkdir -p ../chip_output/chip_cutadapt &&
        cutadapt -a AGATCGGAAGAGC -o {output} {input}
        """
            

#connect chain cutadapt ---> fastqc
#seperate depedancies

rule fastqc:
        input:
            lambda wildcards: get_cut_input(wildcards)
            # wildcards are only available when Snakemake exectus a rule
            #When parsing the object wildcards doe snot exist yet
            #lamda essentially delays the function fun until the rule cutadapt has been exectuted
            
        output:
            "../chip_output/chip_fastqc_results/sim_reads_fastqc.html",
            "../chip_output/chip_fastqc_results/sim_reads_fastqc.zip"
        
        threads: 4
        
        shell:
            "mkdir -p ../chip_output/chip_fastqc_results && fastqc --outdir ../chip_output/chip_fastqc_results -t {threads} {input} - > {output}"
 
#BIG NOTE ONCE FINISHED THIS WILL HAVE TO BE UPDATED FOR LARGER FILES           


#Aligning the cut_reads using bowtie2
#fix up the chip-seq script to use Chr1 instead of a simmed ref genome


# connect chain cutadapt ----> fastqc
#                          |
#                          |---->align_reads

# Similar to the conditional issue with cutadapt and making this script more generalizable (sim_reads vs reals_reads)
# We have to make a bowtie input function due to way snakemake will parse then execute the rules
# This similar to what had to happen with the fastqc condition and rule.
#Personal Note. Very interesting to learn more about the python/snakemake interactions


rule bowtie2_alignment:
        input:
            fastq= "../data/sim_reads.fastq",
            reference="../sim_data/inputs/chr1_limit.fa"
        
        output:
            "../chip_output/aligned_chip_reads/chip_alignments.sam"
    
        shell:
            """
            mkdir -p ../chip_output/aligned_chip_reads &&
            bowtie2-build ../sim_data/inputs/chr1_limit.fa ../chip_output/aligned_chip_reads/chr1_limit &&
            bowtie2 -x ../chip_output/aligned_chip_reads/chr1_limit -q -U {input.fastq} -S {output} --local -p 8
            """
# SAM --(SAMtools view)--> BAM --(SAMtools sort)--> Sorted BAM --(SAMtools rmdup)--> Deduplicated BAM

rule prepsam_deduplicate:
        input:
            sam="../chip_output/aligned_chip_reads/chip_alignments.sam"
             
        output:
            sorted_bam="../chip_output/sorted_bam/chip_sorted.bam",
            deduplicated_bam="../chip_output/sorted_bam/chip_sorted_deduplicated.bam"
            
        shell:
            """
            mkdir -p ../chip_output/sorted_bam &&
            samtools view -b -S {input.sam} | samtools sort -o {output.sorted_bam} &&
            samtools index {output.sorted_bam} | samtools markdup -r {output.sorted_bam} {output.deduplicated_bam}
            """
#set a condition later on where there is a condition and if there is no condition for now we have to just get it done
#
rule peak_call:
        input:
            deduplicated_bam="../chip_output/sorted_bam/chip_sorted_deduplicated.bam"
            
        output:
            summits="../chip_output/macs2_output/peak_call_summits.bed"
            
        shell:
            """
            mkdir -p ../chip_output/macs2_output &&
            macs2 callpeak -t {input.deduplicated_bam} -f BAM -n peak_call --outdir ../chip_output/macs2_output --nomodel
            """

# HOMER/ChIPseeker
#input files needed: mm10_chr1.gtf, chr1_limit.fa, peak_call_file.bed
rule homer:
        input:
            summits="../chip_output/macs2_output/peak_call_summits.bed",
            gtf="../sim_data/inputs/chr1_mm10_ncbirefseq.gtf"
        output:
            ann_peaks="../chip_output/mac2_output/ann_peaks.txt"
        shell:
            """
            annotatePeaks.pl {input.summits} mm10 -gtf {input.gtf} > {output.ann_peaks}
            """
